default: 00 01 02 03 04

# communication

00:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
01:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
02:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)

# error handling

03:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
04:
	LOGGING_LEVEL=INFO DEBUG=1 python $(shell echo $@*.py)
